### ISSUE TITLE
Datum Format for nice day not working 

### ISSUE THREAD

**Issue by thilgertbo** [david-szabo97/grav-plugin-admin-addon-revisions#10]
In thre revision page i foundsomething like this::
20170819-144114 (19 NICETIME.MINUTE_PLURAL NICETIME.AGO)

**Comment by david-szabo97** [comment]
Hi there! Which language are you using?

**Comment by thilgertbo** [comment]
Hi,

German is it

Mit freundlichen Grüßen

Hilgert configuration
Thomas Hilgert
________________________________

**Comment by david-szabo97** [comment]
Strange, it should work. Translations for nicetime filter is supported since Grav version 0.9.44.

**Comment by david-szabo97** [comment]
@thilgertbo Is this still relevant?

**Comment by thilgertbo** [comment]
Yes it is still there no showstopper just funny if it is a grab problem just ignore it. I like your extension and it has no other problem

Mit freundlichen Grüßen

Hilgert configuration
Thomas Hilgert
________________________________

**Comment by david-szabo97** [comment]
Do you have any sensitive data on your website? If you don't have any you
could send me your website zipped so I can give it a check. I can't
reproduce the error but I will give it one more shot.

If you are willing to pass me your website zipped, please do it so to my
email: david.szabo97@gmail.com

Thank you!

**Comment by thilgertbo** [comment]
Hi David,

here comes what you ask for 😊

http://www.hilgert.de/msp/hilgert.zip




Von: Dávid Szabó [mailto:notifications@github.com]
Gesendet: Dienstag, 29. August 2017 10:53
An: david-szabo97/grav-plugin-admin-addon-revisions <grav-plugin-admin-addon-revisions@noreply.github.com>
Cc: Thomas Hilgert <Thomas.Hilgert@hilgert.de>; Mention <mention@noreply.github.com>
Betreff: Re: [david-szabo97/grav-plugin-admin-addon-revisions] Datum Format for nice day not working (#10)

Do you have any sensitive data on your website? If you don't have any you
could send me your website zipped so I can give it a check. I can't
reproduce the error but I will give it one more shot.

If you are willing to pass me your website zipped, please do it so to my
email: david.szabo97@gmail.com

Thank you!

**Comment by david-szabo97** [comment]
@thilgertbo 
Finally found the culprit 😄 
Translations are disabled on your site. `system.yaml` -> `languages.translations` set to `true`. Or through admin panel: `Einstellungen` -> `System` -> `Sprachen` -> `Übersetzungen aktivieren`

**Comment by thilgertbo** [comment]
Hi David,

works like designed 😊
Sorry for bothering you and thanks for your help.

Mit freundlichen Grüßen

Hilgert configuration
Thomas Hilgert

Von: Dávid Szabó [mailto:notifications@github.com]
Gesendet: Mittwoch, 30. August 2017 18:36
An: david-szabo97/grav-plugin-admin-addon-revisions <grav-plugin-admin-addon-revisions@noreply.github.com>
Cc: Thomas Hilgert <Thomas.Hilgert@hilgert.de>; Mention <mention@noreply.github.com>
Betreff: Re: [david-szabo97/grav-plugin-admin-addon-revisions] Datum Format for nice day not working (#10)


@thilgertbo<https://github.com/thilgertbo>
Finally found the culprit 😄
Translations are disabled on your site. system.yaml -> languages.translations set to true. Or through admin panel: Einstellungen -> System -> Sprachen -> Übersetzungen aktivieren
