### ISSUE TITLE
.revs folder not  deleted after uninstall

### ISSUE THREAD

**Issue by axel-rank** [david-szabo97/grav-plugin-admin-addon-revisions#11]
Hi  David,
if you uninstall the plugin in admin the .revs folder(s) and content are not deleted. You have to delete all of them manually.

**Comment by david-szabo97** [comment]
Hi there!

I have added a 'Delete All' button to the 'Revisions' page. You can use that to get rid of them.

Unfortunately I can't do it on uninstall because there is an issue with the code inside Grav. I will push a fix to Grav.
