### ISSUE TITLE
Add option to neglect media / certain pages

### ISSUE THREAD

**Issue by martynvandijke** [david-szabo97/grav-plugin-admin-addon-revisions#12]
Hi, I store albums using grav as separate pages with media.
Using this plugin every photo gets copied into a .rev folder, since I have a large album size of +- 2gb this is not wanted.
Would you therefore add the option to neglect media or certain pages ?

**Comment by david-szabo97** [comment]
Hi there! Sure, I will add an option for that next week.

**Comment by david-szabo97** [comment]
Pushed v1.3.0
Now you can add ignore patterns in the plugin configuration.

Here is an example how you can ignore all png and jpg files in the 'test' page.
```
/pages\/test\/(.*).png$/
/pages\/test\/(.*).jpg$/
```
