### ISSUE TITLE
Can't access /admin/user/username page when plugin is activated

### ISSUE THREAD

**Issue by Laynee** [david-szabo97/grav-plugin-admin-addon-revisions#13]
When I go to the /admin/user/username page and upload an avatar image it throws an error and the page is not accessible anymore. When I disable the plugin, everything is fine. Grav is running on local web server (XAMPP for Windows).

> Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("mkdir(): No such file or directory")."
> 
> Stacktrace:
> #62 Twig_Error_Runtime in D:\Xampp\htdocs\grav\user\plugins\admin\themes\grav\templates\forms\fields\file\file.html.twig:41
> #61 Whoops\Exception\ErrorException in D:\Xampp\htdocs\grav\user\plugins\admin-addon-revisions\src\Revisions.php:46
> #60 mkdir in D:\Xampp\htdocs\grav\user\plugins\admin-addon-revisions\src\Revisions.php:46
> #59 AdminAddonRevisions\Revisions:create in D:\Xampp\htdocs\grav\user\plugins\admin-addon-revisions\admin-addon-revisions.php:160
> #58 Grav\Plugin\AdminAddonRevisionsPlugin:onPageProcessed in D:\Xampp\htdocs\grav\vendor\symfony\event-dispatcher\EventDispatcher.php:184
> #57 call_user_func in D:\Xampp\htdocs\grav\vendor\symfony\event-dispatcher\EventDispatcher.php:184
> #56 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in D:\Xampp\htdocs\grav\vendor\symfony\event-dispatcher\EventDispatcher.php:46
> #55 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in D:\Xampp\htdocs\grav\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php:23
> #54 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:288
> #53 Grav\Common\Grav:fireEvent in D:\Xampp\htdocs\grav\system\src\Grav\Common\Page\Pages.php:269
> #52 Grav\Common\Page\Pages:addPage in D:\Xampp\htdocs\grav\user\plugins\admin\classes\admin.php:1395
> #51 Grav\Plugin\Admin\Admin:getPage in D:\Xampp\htdocs\grav\user\plugins\admin\classes\admin.php:1353
> #50 Grav\Plugin\Admin\Admin:page in D:\Xampp\htdocs\grav\user\plugins\admin\classes\admin.php:1330
> #49 Grav\Plugin\Admin\Admin:getPagePathFromToken in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:677
> #48 call_user_func_array in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:677
> #47 Twig_Template:getAttribute in D:\Xampp\htdocs\grav\cache\twig\6f\6f0645eb1d60c0a43c1e60fb7f3605f3f90fbf3b72031351af5f9971170a31a9.php:278
> #46 __TwigTemplate_07b516ebb6aab53cb005fb3f8b8f7705c853b0797bdff5cb00d3032cccfbe5e3:getpreview in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:677
> #45 call_user_func_array in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:677
> #44 Twig_Template:getAttribute in D:\Xampp\htdocs\grav\cache\twig\6f\6f0645eb1d60c0a43c1e60fb7f3605f3f90fbf3b72031351af5f9971170a31a9.php:88
> #43 __TwigTemplate_07b516ebb6aab53cb005fb3f8b8f7705c853b0797bdff5cb00d3032cccfbe5e3:block_input in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #42 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\6f\6f905b3926dff55e433e8a049a18cfd0d167afa69cf4d2d36f9eb541df6737ab.php:230
> #41 __TwigTemplate_366afb69ed76b03de32b2a238ab8fa97f712b89dadcc21ecf147cb05d3925a0c:block_group in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #40 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\6f\6f905b3926dff55e433e8a049a18cfd0d167afa69cf4d2d36f9eb541df6737ab.php:158
> #39 __TwigTemplate_366afb69ed76b03de32b2a238ab8fa97f712b89dadcc21ecf147cb05d3925a0c:block_contents in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #38 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\6f\6f905b3926dff55e433e8a049a18cfd0d167afa69cf4d2d36f9eb541df6737ab.php:72
> #37 __TwigTemplate_366afb69ed76b03de32b2a238ab8fa97f712b89dadcc21ecf147cb05d3925a0c:block_field in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #36 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\6f\6f905b3926dff55e433e8a049a18cfd0d167afa69cf4d2d36f9eb541df6737ab.php:52
> #35 __TwigTemplate_366afb69ed76b03de32b2a238ab8fa97f712b89dadcc21ecf147cb05d3925a0c:doDisplay in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:432
> #34 Twig_Template:displayWithErrorHandling in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:403
> #33 Twig_Template:display in D:\Xampp\htdocs\grav\cache\twig\6f\6f0645eb1d60c0a43c1e60fb7f3605f3f90fbf3b72031351af5f9971170a31a9.php:32
> #32 __TwigTemplate_07b516ebb6aab53cb005fb3f8b8f7705c853b0797bdff5cb00d3032cccfbe5e3:doDisplay in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:432
> #31 Twig_Template:displayWithErrorHandling in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:403
> #30 Twig_Template:display in D:\Xampp\htdocs\grav\cache\twig\43\43ee690461aaf8eed543948be1b040d7336fee33df7691cb8fdb2b4a6fdb974a.php:71
> #29 __TwigTemplate_7f52834e3a83e92a004a94ef00fbbf861cd054240524dc56fbb5c6e4d0530507:doDisplay in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:432
> #28 Twig_Template:displayWithErrorHandling in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:403
> #27 Twig_Template:display in D:\Xampp\htdocs\grav\cache\twig\c5\c59bf57b9095c5d646e570fcb015864a805ceee11fcd37b0fe0819a5c88952d2.php:136
> #26 __TwigTemplate_59baf9c6f755dd67b152d360ca6a898d9c00518c1f1131b203c0f342c4041743:block_content in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #25 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\37\379057ecd3fd5a0c068df3313f4cd36db2ea81033070aa4a214aa8f97b6d65b0.php:215
> #24 __TwigTemplate_155309ecff152fc3ca479609aa91c9571590091f0cc9538f16de16b6bb86704b:block_page in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #23 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\37\379057ecd3fd5a0c068df3313f4cd36db2ea81033070aa4a214aa8f97b6d65b0.php:160
> #22 __TwigTemplate_155309ecff152fc3ca479609aa91c9571590091f0cc9538f16de16b6bb86704b:block_body in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:215
> #21 Twig_Template:displayBlock in D:\Xampp\htdocs\grav\cache\twig\37\379057ecd3fd5a0c068df3313f4cd36db2ea81033070aa4a214aa8f97b6d65b0.php:47
> #20 __TwigTemplate_155309ecff152fc3ca479609aa91c9571590091f0cc9538f16de16b6bb86704b:doDisplay in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:432
> #19 Twig_Template:displayWithErrorHandling in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:403
> #18 Twig_Template:display in D:\Xampp\htdocs\grav\cache\twig\58\58ef7b7e43b30a474e5890df9a4ac9b92d7847afa6870ba0522a9079368852d7.php:23
> #17 __TwigTemplate_7c4f19a8f7219a74f7b8eb609587a0e6c42ad808ea2ba15f075a9c91ec78ec47:doDisplay in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:432
> #16 Twig_Template:displayWithErrorHandling in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:403
> #15 Twig_Template:display in D:\Xampp\htdocs\grav\cache\twig\c5\c59bf57b9095c5d646e570fcb015864a805ceee11fcd37b0fe0819a5c88952d2.php:36
> #14 __TwigTemplate_59baf9c6f755dd67b152d360ca6a898d9c00518c1f1131b203c0f342c4041743:doDisplay in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:432
> #13 Twig_Template:displayWithErrorHandling in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:403
> #12 Twig_Template:display in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Template.php:411
> #11 Twig_Template:render in D:\Xampp\htdocs\grav\vendor\twig\twig\lib\Twig\Environment.php:363
> #10 Twig_Environment:render in D:\Xampp\htdocs\grav\system\src\Grav\Common\Twig\Twig.php:349
> #9 Grav\Common\Twig\Twig:processSite in D:\Xampp\htdocs\grav\system\src\Grav\Common\Service\OutputServiceProvider.php:27
> #8 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in D:\Xampp\htdocs\grav\vendor\pimple\pimple\src\Pimple\Container.php:118
> #7 Pimple\Container:offsetGet in D:\Xampp\htdocs\grav\system\src\Grav\Common\Processors\RenderProcessor.php:19
> #6 Grav\Common\Processors\RenderProcessor:process in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:132
> #5 Grav\Common\Grav:Grav\Common\{closure} in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:379
> #4 Grav\Common\Grav:Grav\Common\{closure} in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:355
> #3 call_user_func_array in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:355
> #2 Grav\Common\Grav:__call in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:133
> #1 Grav\Common\Grav:measureTime in D:\Xampp\htdocs\grav\system\src\Grav\Common\Grav.php:133
> #0 Grav\Common\Grav:process in D:\Xampp\htdocs\grav\index.php:52

**Comment by david-szabo97** [comment]
Fixed in v1.3.2
Thank you!
