### ISSUE TITLE
Render Errror

### ISSUE THREAD

**Issue by s0kil** [david-szabo97/grav-plugin-admin-addon-revisions#15]
![screenshot from 2018-02-20 16-09-02](https://user-images.githubusercontent.com/24403355/36449295-6a875948-1658-11e8-8766-a6f8a32e9a8b.png)

**Comment by david-szabo97** [comment]
Hi!

I can't reproduce this.

Do you have any other information available?
What language are you using?
Are you on the latest version?

**Comment by david-szabo97** [comment]
Closed due to inactivity.
