### ISSUE TITLE
Template "revisions.html.twig" is not defined.

### ISSUE THREAD

**Issue by phideas** [david-szabo97/grav-plugin-admin-addon-revisions#16]
Got this error after clicking on Revisions link on sidebar in Admin Panel.
Plugin reinstall doesn't help.

` RuntimeException (400)
Template "revisions.html.twig" is not defined.`

**Comment by david-szabo97** [comment]
Hi!

I can't reproduce this in Grav v1.4.1 - Admin v1.7.1 - Revisions v1.3.2.

Do you have any other information available? Are you on the latest version?

**Comment by david-szabo97** [comment]
Closed due to inactivity.
