### ISSUE TITLE
Is not compatible with Events plugin

### ISSUE THREAD

**Issue by lufik** [david-szabo97/grav-plugin-admin-addon-revisions#17]
Revisions plugin is not compatible with the Events plugin.

I installed both and created repeatable event (e.g. weekly one).
From that time every page (view) fails on mkdir because it tries
create .revs dir under "virtual" directory (as events are cloned in
case or repeatable events - but not written to hdd).

Quick and dirty fix is to skip non-existing pages in
user/plugins/admin-addon-revisions/admin-addon-revisions.php:
-  public function onPageProcessed(Event $e)
    below check if page.id exists I added:
```php
public function onPageProcessed(Event $e) {
    $page = $e['page'];

    if (!$page->id()) {
      return;
    }

    if (!$page->exists()) {
      return;
    }

    $this->debugMessage('--- Admin Addon Revision - Analyzing \'' . $page->title(). '\' ---');
```
However I'm not sure if it's the right fix.

**Comment by david-szabo97** [comment]
Fixed in v1.3.3
Thanks for reporting.

Reopen the issue if necessary.
