### ISSUE TITLE
Plugin is slowing down the entire admin area

### ISSUE THREAD

**Issue by codiflow** [david-szabo97/grav-plugin-admin-addon-revisions#18]
Unfortunately after activating this addon every request in the admin area takes more than 100% longer than it took before. That drives me nuts... :/

This is a list of all **activated** plugins:

- Admin Panel  v1.8.11
- Admin Addon Revisions v1.3.2
- Admin Addon User Manager v2.1.6
- Archives  v1.5.1
- Auto Date  v1.0.2
- Auto SEO v1.3.5
- Comments  v1.2.7
- Core Service Manager v1.0.12
- Email  v2.7.1
- Error  v1.6.1
- Featherlight  v1.5.0
- Feed  v1.6.2
- Form  v2.16.3
- Image Collage v1.0.4
- Login  v2.7.3
- Markdown Color  v1.0.1
- Markdown Notices  v1.0.1
- Markdown Spoilers v1.0.0
- Markdown Task Lists v1.0.0
- Page Inject  v1.3.0
- Pagination  v1.4.1
- Problems  v2.0.0
- Quick Save v0.1.7
- Related Pages  v1.2.0
- Responsive Images v1.0.0
- Scheduler v1.0.0
- Simple Responsive Tables v1.1.1
- SimpleSearch  v1.14.1
- Sitemap  v1.9.1
- Social & SEO Meta Tags v1.1.1
- Twig Extensions v1.0.2
- Unitegallery v1.1.3

I'm running the newest version of GRAV v1.5.3

I was using the Chromium Network panel to take the time.

With your plugin **activated** loading "/admin/pages" takes:
![image](https://user-images.githubusercontent.com/43847817/46871299-415af700-ce31-11e8-8c45-65f1d19a9069.png)

With your plugin **deactivated** loading "/admin/pages" takes:
![image](https://user-images.githubusercontent.com/43847817/46871258-2c7e6380-ce31-11e8-81f4-eb056aa51afd.png)

And here are my plugin settings:
![image](https://user-images.githubusercontent.com/43847817/46871374-83843880-ce31-11e8-80b1-3709136c6e05.png)

I think the issue is because you render the page "twice" on php side so it takes longer. Is it possible to disable this for the admin area and activate it for the editable pages only?

**Comment by david-szabo97** [comment]
I am not sure about this. Also what does "render the page twice" mean? The plugin isn't doing anything until you save a page. I tried to reproduce, but I am getting the same loading speed.

**Comment by codiflow** [comment]
I will have a more detail look at it later. Stay tuned.

**Comment by codiflow** [comment]
After I activated **Caching** of the Admin Plugin the problem seems to be gone.

I'll keep an eye on this.
