### ISSUE TITLE
Error: Allowed memory size exhausted

### ISSUE THREAD

**Issue by peter7n** [david-szabo97/grav-plugin-admin-addon-revisions#19]
<img width="2578" alt="screen shot 2018-12-10 at 1 12 04 pm" src="https://user-images.githubusercontent.com/14829959/49762377-6d062c00-fc7e-11e8-9e6a-26b61f0b347d.png">

Error occurs randomly under normal usage when clicking on certain past revisions; revisions are not particularly large files

Error thrown by Diff.php

**Comment by david-szabo97** [comment]
This happens in some circumstances... The diff library is very straightforward, we might need to replace it with a more sophisticated one.
