### ISSUE TITLE
Little bug in Configuration Tab

### ISSUE THREAD

**Issue by matrixino** [david-szabo97/grav-plugin-admin-addon-revisions#21]
I noticed a bug in the Admin Addon Revisions v1.3.3 plugin on lastets Grav&AdminPlugin. When enabled I'm getting asked if I want so save or lose changes when moving from the default Configuration Tab (System) even if no changes has been made (just loaded). It happens only when switching from System tab to any other and only if this module is activated.

**Comment by david-szabo97** [comment]
Thanks, it will be fixed in next release.
