### ISSUE TITLE
.revs/ folders re-added even when plugin disabled

### ISSUE THREAD

**Issue by paulrudy** [david-szabo97/grav-plugin-admin-addon-revisions#25]
After I disabled the plugin and deleted the revisions folders `.revs/`, they continued to be added to my pages' directories. This behavior wouldn't stop until I actually removed the plugin.

I'm on grav 1.7.0-rc.10

**Comment by david-szabo97** [comment]
Can't reproduce on Grav v1.7.42.3 - Admin v1.10.42
Reopen if necessary
