### ISSUE TITLE
Umlauts not displayed correctly in diffs

### ISSUE THREAD

**Issue by Markus00000** [david-szabo97/grav-plugin-admin-addon-revisions#26]
What should be displayed:

    ---
    title: Test
    date: '11:05 22-06-2020'
    ---
    
    a ä
    o ö
    u ü

What is displayed:

    ---
    title: Test
    date: '11:05 22-06-2020'
    ---
    
    a ��
    o ��
    u ��

HTML:

    <pre class="revision-change__changes">---
    title: Test
    date: '11:05 22-06-2020'
    ---
    
    a<span class="inserted"> </span><span class="inserted">�</span><span class="inserted">�</span>
    o<span class="inserted"> </span><span class="inserted">�</span><span class="inserted">�</span>
    u<span class="inserted"> </span><span class="inserted">�</span><span class="inserted">�</span></pre>

**Comment by david-szabo97** [comment]
Fixed in https://github.com/david-szabo97/grav-plugin-admin-addon-revisions/commit/8e9fd88dee2a69ee949fc20bbf7bcfc9e1ad1726 (released in v2.0.0)

Please reopen if you find any other issues with multibyte strings
