### ISSUE TITLE
mkdir() not allowed for plugin://login/pages/.revs

### ISSUE THREAD

**Issue by gfvh** [david-szabo97/grav-plugin-admin-addon-revisions#28]
Hi

Did install according to instructions. I can see that directories for first time are actually created but with website refresh, whole site not working, gives error message: mkdir() not allowed for plugin://login/pages/.revs

Conf:

````
enabled: true
debug: false
directory: .revs
limit:
  maximum: 50
  older: 1 year
````

Plugin is latest stable what grav cli download

Grav v1.7.37.1
Admin Addon Revisions [v1.4.0]

Please help

**Comment by david-szabo97** [comment]
Fixed in https://github.com/david-szabo97/grav-plugin-admin-addon-revisions/commit/b9b839f74f32fbff9e57a50813ce20a39861afa1 released in v2.0.0

Please reopen if necessary
