### ISSUE TITLE
Mkdir() not allowed for plugin://login/pages/.revs

### ISSUE THREAD

**Issue by ramsnerm** [david-szabo97/grav-plugin-admin-addon-revisions#32]
**Issue Description:**

While working with the **Plugin Admin Revisions**, I encountered an issue where enabling 2FA causes the following error to occur during the login process:

`mkdir() not allowed for plugin://login/pages/.revs/...`

If 2FA is disabled, everything functions as expected. However, when 2FA is active, the error prevents me from completing the login.

---

I have already tried the following steps based on the points mentioned above, but none of them resolved the issue:

- Ensuring correct directory permissions (including setting them to 777 temporarily).
- Manually configuring streams in system.yaml
- Attempting to redirect 2FA data to a different, writable path.
- Disabling Admin revisions during the login process while re-enabling them after login.
- Clearing the cache multiple times after every change.
- Testing with various configurations of both 2FA and Admin revisions.

Despite all efforts, the error persists, and 2FA cannot function alongside Admin revisions during the login process.

---

**Observation:**

Interestingly, if Admin revisions are activated **after login**, both features work without any issues. The error seems to occur specifically during the login phase when both 2FA and Admin revisions are active.

---

**Environment Details:**
- Grav version: 1.7.48
- Login plugin version: 3.7.9
- Admin Revision Plugin version: Release v2.0.1)
- PHP version: 8.2

**Comment by david-szabo97** [comment]
Thank you for the thorough bug report @ramsnerm ! I'm not quite sure what's the best way to check for "normal pages".
Released a fix in https://github.com/david-szabo97/grav-plugin-admin-addon-revisions/releases/tag/2.0.2  Probably not the best solution but should solve the issue.

Can you please try the new version? Thank you!

**Comment by ramsnerm** [comment]
Thank you for the fix. Everything works as it is expected. I wish you a Happy New Year!
