### ISSUE TITLE
Installing this breaks entire website.

### ISSUE THREAD

**Issue by iggbodiam** [david-szabo97/grav-plugin-admin-addon-revisions#4]
**Steps:**
- list of plugins and versions that I have on the website
    -  Admin Panel v1.4.2
    - Archives v1.5.1
    - Auto Date v1.0.1
    - Aviary Image Editor v1.0.0
    - Comments v1.2.7
    - Email v2.6.0
    - Error v1.6.0
    - Form v2.7.0
    - Login v2.3.1
    - Markdown Notices v1.0.0
    - Problems v1.4.7
    - reCAPTCHA Contact v2.1.1
    - Shortcode Core v2.6.0
    - Shortcode UI v2.2.5
    - Unitegallery v1.1.3
- Install Admin-Addon-Revisions existing version.

**is:**
- All website pages are blank.
- Inspect element console error: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

Note: Issue resolved by deleting the plugin's folder under user/plugins/

**Should:**
- the website should function.
- the plugin should function.

**Comment by david-szabo97** [comment]
Hi there!
Thank you for your bug report.

Though I cannot reproduce the issue. I installed a fresh a Grav then installed all the plugins you listed above. Everything works fine. Is there anything in your `logs/grav.log` ?

**Comment by iggbodiam** [comment]
I attached the logs here, I didn't notice anything specific but maybe you'll find something
[grav.log.txt](https://github.com/david-szabo97/grav-plugin-admin-addon-revisions/files/1035763/grav.log.txt)

I also learned that the error is 500.
If it also helps, I installed using /admin/plugins/install User-interface.

**Comment by david-szabo97** [comment]
Unfortunately, those are unrelated. Can you clear the log and try the plugin again?
You should try enabling the error displaying too, inside `user/config/system.yaml`.
```yaml
errors:
  display: true
  log: true
```

Thank you!

**Comment by david-szabo97** [comment]
Because of inactivity I will take this issue as resolved. If the issue still remains please comment and I'll reopen it.
