### ISSUE TITLE
Lots of debug messages in the grav debugger

### ISSUE THREAD

**Issue by CSixtyFour** [david-szabo97/grav-plugin-admin-addon-revisions#7]
Thanks for the really useful plugin!

I've found it tricky debugging other issues sometimes because this plugin outputs a lot of debug (info) messages by default. Therefore I've created some PRs to add a menu option to disable this output. I'm dropping the output of the message log but haven't messed with any of the actual functionality of the plugin.

**Comment by david-szabo97** [comment]
Hi there!

Thank you for your PRs. You are absolutely correct about the message log. I commented on your PRs, please make those changes and I'll happily merge them and do a release.

Thank you!

**Comment by david-szabo97** [comment]
Implemented by v1.1.0 (https://github.com/david-szabo97/grav-plugin-admin-addon-revisions/commit/edc851c7b566373c53f83d56c1b603fd31cdf4d0)
