### ISSUE TITLE
 Parse error: syntax error, unexpected '.', expecting ',' or ';

### ISSUE THREAD

**Issue by michaeldn** [david-szabo97/grav-plugin-admin-addon-revisions#9]
Upon Installing I receive the error: 

Parse error: syntax error, unexpected '.', expecting ',' or '; in /home/mydomain/user/plugins/admin-addon-revisions/admin-addon-revisions.php on line 19

The parse error is not accurate but still breaks the site/admin panel.

**Comment by david-szabo97** [comment]
v1.1.1 fixes this.
The code was relying on PHP 5.6 feature.

Thank you, I'll leave this open till you approve it is fixed.

**Comment by michaeldn** [comment]
Yes fixed! Thank you kindly this feature makes editing much more simple.
